//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DatabaseFirst_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_Usuarios
    {
        private string genero;
        private int activo;

        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Correo { get; set; }
        public string Genero
        { 
            get
            {
                //Console.WriteLine("GENERO" + this.genero);
                return this.genero;
            }
            set
            {
                switch (value)
                {
                    case "0":
                        genero = "M";
                        break;
                    case "1":
                        genero = "F";
                        break;
                    default:
                        genero = value;
                        break;
                }           
            }
        }

        //[Display(Name = "Terms and Conditions")]
        //[Range(typeof(bool), "true", "true", ErrorMessage = "You gotta tick the box!")]
        //public bool Activo { get; set; }
        public Nullable<int> Activo
        {
            get
            {
                return this.activo;
            }
            set
            {
                switch (Convert.ToString(value))
                {
                    case "1":
                        activo = 1;
                        break;
                    default:
                        genero = Convert.ToString(value);
                        break;
                }
            }
        }
    }
}
